#ifndef HEIGHTMAPPER_CONSTANTS_H
#define HEIGHTMAPPER_CONSTANTS_H

// TODO: remove these
const int COLOR_WHITE = 0;
const int COLOR_COORDINATE_AXES = 1;
const int COLOR_YELLOW = 2;
const int COLOR_TURQUOISE = 3;

const int COLOR_HEIGHT = 0;

#endif // HEIGHTMAPPER_CONSTANTS_H
